// Master Data 43 BSU Desa Gunung Putri
const dataBSU = [
    { id: 'bsu_mede1', nama: 'BSU MEDE 1', rw: 'RW01', rt: 'RT01', ketua: 'Bapak Slamet' },
    { id: 'bsu_mede2', nama: 'BSU MEDE 2', rw: 'RW01', rt: 'RT02', ketua: 'Ibu Siti' },
    { id: 'bsu_mede3', nama: 'BSU MEDE 3', rw: 'RW01', rt: 'RT03', ketua: 'Bapak Agus' },
    { id: 'bsu_mede4', nama: 'BSU MEDE 4', rw: 'RW01', rt: 'RT04', ketua: 'Ibu Dewi' },
    { id: 'bsu_pelangi_ceria', nama: 'BSU PELANGI CERIA', rw: 'RW02', rt: 'RT01', ketua: 'Bapak Herman' },
    { id: 'bsu_pelangi_2', nama: 'BSU PELANGI 2', rw: 'RW02', rt: 'RT02', ketua: 'Ibu Rina' },
    { id: 'bsu_pelangi_kenanga', nama: 'BSU PELANGI KENANGA', rw: 'RW02', rt: 'RT03', ketua: 'Bapak Joko' },
    { id: 'bsu_pelangi_bunda', nama: 'BSU PELANGI BUNDA', rw: 'RW02', rt: 'RT04', ketua: 'Ibu Tuti' },
    { id: 'bsu_rw03_rt01', nama: 'BSU RW03 RT01', rw: 'RW03', rt: 'RT01', ketua: 'Bapak Eko' },
    { id: 'bsu_rw03_rt02', nama: 'BSU RW03 RT02', rw: 'RW03', rt: 'RT02', ketua: 'Ibu Ani' },
    { id: 'bsu_rw03_rt03', nama: 'BSU RW03 RT03', rw: 'RW03', rt: 'RT03', ketua: 'Bapak Budi' },
    { id: 'bsu_forsila', nama: 'BSU FORSILA', rw: 'RW04', rt: 'RT01', ketua: 'Ibu Wati' },
    { id: 'bsu_berseri_04', nama: 'BSU BERSERI 04', rw: 'RW04', rt: 'RT02', ketua: 'Bapak Dodi' },
    { id: 'bsu_bintang_kejora_1', nama: 'BSU BINTANG KEJORA 1', rw: 'RW05', rt: 'RT01', ketua: 'Ibu Lina' },
    { id: 'bsu_bintang_kejora_2', nama: 'BSU BINTANG KEJORA 2', rw: 'RW05', rt: 'RT02', ketua: 'Bapak Deni' },
    { id: 'bsu_terang', nama: 'BSU TERANG', rw: 'RW06', rt: 'RT01', ketua: 'Ibu Maya' },
    { id: 'bsu_rw06_rt02', nama: 'BSU RW06 RT02', rw: 'RW06', rt: 'RT02', ketua: 'Bapak Rudi' },
    { id: 'bsu_rw06_rt03', nama: 'BSU RW06 RT03', rw: 'RW06', rt: 'RT03', ketua: 'Ibu Erna' },
    { id: 'bsu_rw06_rt04', nama: 'BSU RW06 RT04', rw: 'RW06', rt: 'RT04', ketua: 'Bapak Tono' },
    { id: 'bsu_rw06_rt05', nama: 'BSU RW06 RT05', rw: 'RW06', rt: 'RT05', ketua: 'Ibu Yuni' },
    { id: 'bsu_bersemi_0107', nama: 'BSU BERSEMI 0107', rw: 'RW07', rt: 'RT01', ketua: 'Bapak Hendra' },
    { id: 'bsu_bersemi_07', nama: 'BSU BERSEMI 07', rw: 'RW07', rt: 'RT02', ketua: 'Ibu Ratna' },
    { id: 'bsu_rw07_rt03', nama: 'BSU RW07 RT03', rw: 'RW07', rt: 'RT03', ketua: 'Bapak Feri' },
    { id: 'bsu_rw07_rt04', nama: 'BSU RW07 RT04', rw: 'RW07', rt: 'RT04', ketua: 'Ibu Linda' },
    { id: 'bsu_rw07_rt05', nama: 'BSU RW07 RT05', rw: 'RW07', rt: 'RT05', ketua: 'Bapak Andi' },
    { id: 'bsu_mentari_01', nama: 'BSU MENTARI 01', rw: 'RW08', rt: 'RT01', ketua: 'Ibu Nina' },
    { id: 'bsu_mentari', nama: 'BSU MENTARI', rw: 'RW08', rt: 'RT02', ketua: 'Bapak Taufik' },
    { id: 'bsu_kp_kidoel', nama: 'BSU KP KIDOEL', rw: 'RW09', rt: 'all', ketua: 'Bapak Kidoel' },
    { id: 'bsu_mawarga', nama: 'BSU MAWARGA', rw: 'RW10', rt: 'RT01', ketua: 'Ibu Rose' },
    { id: 'bsu_srikandi', nama: 'BSU SRIKANDI', rw: 'RW10', rt: 'RT02', ketua: 'Bapak Srikandi' },
    { id: 'bsu_rw10_rt03', nama: 'BSU RW10 RT03', rw: 'RW10', rt: 'RT03', ketua: 'Ibu Mega' },
    { id: 'bsu_rw11_rt01', nama: 'BSU RW11 RT01', rw: 'RW11', rt: 'RT01', ketua: 'Bapak Gilang' },
    { id: 'bsu_zalak_2', nama: 'BSU ZALAK 2', rw: 'RW11', rt: 'RT02', ketua: 'Ibu Zalak' },
    { id: 'bsu_rw11_rt03', nama: 'BSU RW11 RT03', rw: 'RW11', rt: 'RT03', ketua: 'Bapak Rizki' },
    { id: 'bsu_rw12_rt01', nama: 'BSU RW12 RT01', rw: 'RW12', rt: 'RT01', ketua: 'Ibu Sari' },
    { id: 'bsu_rw12_rt02', nama: 'BSU RW12 RT02', rw: 'RW12', rt: 'RT02', ketua: 'Bapak Darma' },
    { id: 'bsu_rw12_rt03', nama: 'BSU RW12 RT03', rw: 'RW12', rt: 'RT03', ketua: 'Ibu Ayu' },
    { id: 'bsu_cemerlang_1', nama: 'BSU CEMERLANG 1', rw: 'RW13', rt: 'RT01', ketua: 'Bapak Chandra' },
    { id: 'bsu_cemerlang_2', nama: 'BSU CEMERLANG 2', rw: 'RW13', rt: 'RT02', ketua: 'Ibu Berlian' },
    { id: 'bsu_cemerlang_3', nama: 'BSU CEMERLANG 3', rw: 'RW13', rt: 'RT03', ketua: 'Bapak Gio' },
    { id: 'bsu_rw14_rt01', nama: 'BSU RW14 RT01', rw: 'RW14', rt: 'RT01', ketua: 'Ibu Fira' },
    { id: 'bsu_rw14_rt02', nama: 'BSU RW14 RT02', rw: 'RW14', rt: 'RT02', ketua: 'Bapak Irfan' },
    { id: 'bsu_rw14_rt03', nama: 'BSU RW14 RT03', rw: 'RW14', rt: 'RT03', ketua: 'Ibu Nadia' }
];